//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChiaSeCode_TTV.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Demo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Demo()
        {
            this.NguoiDungs = new HashSet<NguoiDung>();
        }

        [Display(Name = "Mã Demo")]
        public int MaDemo { get; set; }
        [Display(Name = "Tên Demo")]
        [Required(ErrorMessage = "{0} không được để trống")]
        public string TenDemo { get; set; }
        [Display(Name = "Mô tả")]
        [Required(ErrorMessage = "{0} không được để trống")]
        public string MoTa { get; set; }
        [Display(Name = "Ảnh")]
   
        public string Anh { get; set; }
        [Display(Name = "Ngôn ngữ code: ")]
        [Required(ErrorMessage = "{0} không được để trống")]
        public string NgonNgu { get; set; }
        [Display(Name = "Người đăng")]
        [Required(ErrorMessage = "{0} không được để trống")]
        public string NguoiDang { get; set; }
        [Display(Name = "Có đưa lên trang chủ không (ghi 1 là có)")]
        [Required(ErrorMessage = "{0} không được để trống")]
        public Nullable<int> TrangChu { get; set; }
        [Display(Name = "Danh mục")]
        [Required(ErrorMessage = "{0} không được để trống")]
        public Nullable<int> MaDanhMuc { get; set; }
        [Display(Name = "Có cho lên nổi bật không (ghi 2 là có)")]
        public Nullable<int> NoiBat { get; set; }

        public virtual DanhMuc DanhMuc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NguoiDung> NguoiDungs { get; set; }
    }
}
